# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Vinodh Rajasekharan
tagline:          'developer journal'
description:      'Native,Web,Cloud and Mobile apps expert at Microsoft'
url:              http://vinodhr.com 
baseurl:          /

author:
  name:           'Vinodh Rajasekharan'
  url:            https://github.com/vinodhrajasekharan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/vinodhrajasekharan
